// Generated by `pnpm db:gen-types` after Plan 02 schema migration.
// Placeholder so downstream packages compile until then.
export type Database = Record<string, never>;
export type Tables = Record<string, never>;
